#  This file is part of Delaunay triangulation robust implementation.
#
#  Copyright (C) 2010, 2011  Vladimir Rutsky <altsysrq@gmail.com>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

# TODO: Automatically create visualization for tests failed verification.
# TODO: Provide quite COMSTR.
# TODO: Sort test so that at first will be checked new tests (e.g. at 
# first tests without output files).

import os
import os.path
import itertools
import re
import subprocess
import tempfile
import datetime

Import('global_env')
env = global_env.Clone()

failed_tests_limit = 1

class TestFailed(Exception):
    pass

def normalize_output(output):
    output = output.replace('\r', '')

    indices = map(int, output.split())
    assert len(indices) % 3 == 0
    
    triangles = zip(indices, indices[1:], indices[2:])[0::3]
    for idx, tr in enumerate(triangles[:]):
        triangles[idx] = min(tr, (tr[1], tr[2], tr[0]), (tr[2], tr[0], tr[1]))
        
    triangles.sort()
    
    result = "\n".join(map(lambda tr: " ".join(map(str, tr)), triangles))
    if result:
        result += "\n"
    return result

def run_tests(env, target, source):
    app = str(source[0].abspath)
    verificator = str(source[1].abspath)
    
    tests_dir = os.path.dirname(target[0].abspath)
    
    test_files = map(str, source[2:])
    failed_tests = []
    for test_file in test_files:
        test_name = os.path.basename(re.sub(r"\.in$", "", test_file))
        print " *** Running '{0}'".format(test_name)
        
        # Read test input.
        with open(test_file, 'r') as f:
            test_data = f.read()
    
        try:
            test_err_file = os.path.join(tests_dir, test_name + ".err")
            if os.path.exists(test_err_file):
                print "    Remove obsolete error log: '{0}'".format(os.path.relpath(test_err_file))
                os.remove(test_err_file)
        
            # Run DT.
            start_time = datetime.datetime.now()
            try:
                process = subprocess.Popen([app], stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
                stdout, stderr = process.communicate(test_data)
                if len(stderr) > 0:
                    print "      stderr:\n{0}".format(stderr)
                    with open(test_err_file, 'w') as f:
                        f.write(stderr)
                if process.returncode != 0: 
                    print "Test failed with error code {0}".format(
                        process.returncode)
                    if len(stdout) > 0:
                        print "      stdout:\n{0}".format(stdout)
                    raise TestFailed()
            finally:
                time = datetime.datetime.now() - start_time
                print "    triangulation time:", time

            # Write result.
            test_result_file = os.path.join(tests_dir, test_name + ".out")
            output = normalize_output(stdout)
            with open(test_result_file, 'w') as f:
                f.write(output)
            
            # Verify result.
            verification_err_file = os.path.join(tests_dir, test_name + ".ver_err")
            if os.path.exists(verification_err_file):
                print "    Remove obsolete verification error log: '{0}'".format(os.path.relpath(verification_err_file))
                os.remove(verification_err_file)
            
            start_time = datetime.datetime.now()
            try:
                process = subprocess.Popen([verificator, test_file, test_result_file],
                    stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
                verification_stdout, verification_stderr = process.communicate()
                if len(verification_stdout) > 0:
                     print "      stdout:\n{0}".format(verification_stdout)
                if len(verification_stderr) > 0:
                     print "      stderr:\n{0}".format(verification_stderr)
                     with open(test_err_file, 'w') as f:
                         f.write(verification_stderr)

                if process.returncode != 0:
                    print "Verification returned error code {0}.".format(
                        process.returncode)
                    raise TestFailed()
            finally:
                time = datetime.datetime.now() - start_time
                print "    verification time: ", time
            
            # Compare with precomputated result.
            correct_result_file = os.path.join(tests_dir, test_name + ".valid_out")
            if os.path.exists(correct_result_file):
                with open(correct_result_file, 'r') as f:
                    test_correct_result = f.read().replace('\r', '')
                if test_correct_result != output:
                    print "    Test failed due to different output."
                    raise TestFailed()

        except TestFailed:
            failed_tests.append(test_name)
            print
            if len(failed_tests) >= failed_tests_limit:
                print "Number of failed test exceeded {0}. "\
                    "Skipping left tests.".format(failed_tests_limit)
                break
        else:
            pass
      
    if len(failed_tests) == 0:
        with open(str(target[0]), 'w') as f:
            f.write(str(datetime.datetime.now()))
        print "All tests succeded"
    else:
        print "Following tests failed:\n  " + ", ".join(failed_tests)

test_files = Glob("*.in", strings=True)
tests_cmd = Command(".passed", 
    [env.delaunay, env.verificator] + test_files, 
    run_tests, COMSTR="Running tests.")
Clean(tests_cmd, 
    map(lambda f: re.sub(r"\.in$", ".out", f), test_files) +
    map(lambda f: re.sub(r"\.in$", ".err", f), test_files) +
    map(lambda f: re.sub(r"\.in$", ".ver_err", f), test_files))

# vim: set filetype=python et ts=4 sw=4:
