#  This file is part of traffic lights model development and verification.
#
#  Copyright (C) 2010  Vladimir Rutsky <altsysrq@gmail.com>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

import os.path
import itertools

Import("env")

sources = Glob("*.pml", strings=True)

automata_source_node = env.Command("pan.c", sources, "spin -a -v main.pml", chdir=True)
Clean(automata_source_node, ["pan.b", "pan.m", "pan.h", "pan.t", "pan.tmp"])

verify_basic_safety = env.Command("verify_basic_safety", sources,
    "spin -a -v main.pml && "
    "gcc -w -o pan -D_POSIX_SOURCE -DMEMLIM=2048 -DSAFETY -DNOCLAIM -DXUSAFE -DNOFAIR pan.c && "
    "echo && "
    "time -v ./pan -v -m2000000 -w19 -c1 -b -v", chdir=True)
Clean(verify_basic_safety, ["pan.b", "pan.m", "pan.h", "pan.t", "pan.tmp", "pan"])

safety_01 = env.Command("safety_01.ltl", [],
    "spin -f '! ([] (!accident_01))' > safety_01.ltl",
    chdir=True)

verify_safety_01 = env.Command("verify_safety_01", safety_01,
    "spin -a -N safety_01.ltl -v main.pml && "
    "gcc -w -o pan -D_POSIX_SOURCE -DMEMLIM=2048 -DXUSAFE -DNOFAIR pan.c && "
    "echo && "
    "time -v ./pan -v -m2000000 -w19 -a -c1", chdir=True)
Clean(verify_safety_01, ["pan"])

verify_liveness_progress = env.Command("verify_liveness_progress", automata_source_node,
    "gcc -w -o pan -D_POSIX_SOURCE -DMEMLIM=2048 -DNP -DNOCLAIM -DXUSAFE -DNOFAIR pan.c && "
    "echo && "
    "time -v ./pan -v -m2000000 -w19  -l -c1", chdir=True)
Clean(verify_liveness_progress, ["pan"])

Default(automata_source_node)
