#  This file is part of traffic lights model development and verification.
#
#  Copyright (C) 2010  Vladimir Rutsky <altsysrq@gmail.com>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

import os.path
import itertools

Import("env")

sources = Glob("*.pml", strings=True)

automata_source_node = env.Command("pan.c", sources, "spin -a main.pml", chdir=True)
Clean(automata_source_node, ["pan.b", "pan.m", "pan.h", "pan.t"])

automata_binary = env.Command("pan", automata_source_node, "cc -o pan pan.c", chdir=True)

#env.Builder("run", automata_binary, action="./pan", chdir=True)

Default(automata_binary)
