#
#  Copyright (C) 2010  Vladimir Rutsky <altsysrq@gmail.com>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

import os

env = Environment(tools=["default"])

env['ENV']['HOME'] = os.environ['HOME']
pdfOutput = env.PDF(target='50572_Rutsky_research_work.pdf',
    source='50572_Rutsky_research_work.tex')
#Depends(pdfOutput,Split('presentation.tex bibliography.bib'))

pdfOutput = env.PDF(target='5057-12_Rutsky_research_work_report.pdf', 
    source='5057-12_Rutsky_research_work_report.tex')

# vim: set filetype=python ts=4 sw=4 et:
