#  This program is part of network emulation test model.
#
#  Copyright (C) 2010  Vladimir Rutsky <altsysrq@gmail.com>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

import os

Import('env')

python_sources = list(
    set(Glob("*.py", strings=True)) - 
    set(["setup.py", "setup_cx-freeze.py"]))

sources = \
    python_sources + \
    Glob(os.path.join("forms", "*.ui"), strings=True) + \
    Glob(os.path.join("i18n", "*.ts"), strings=True)

build_cx_freeze = env.Command("build_cx-freeze", sources,
    "python setup_cx-freeze.py build",
    chdir=True)
Clean(build_cx_freeze, ['build'])

lupdate = env.Command("lupdate",
    ["network_model.pro"], # TODO
    "pylupdate4 network_model.pro",
    chdir=True)

Default()

# vim: set filetype=python ts=4 sw=4 et:
