#  This file is part of Delaunay triangulation robust implementation.
#
#  Copyright (C) 2010, 2011  Vladimir Rutsky <altsysrq@gmail.com>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

import os.path
import itertools

import SCons.Util

Import('global_env')
env = global_env.Clone()

#env['Gch'] = env.Gch('precompiled.hpp')[0]

configuration = ARGUMENTS.get('conf', None)
if configuration not in ['release', 'valgrind', 'gprof']:
  configuration = 'debug'

# Common build flags.
env.MergeFlags(
    env.ParseFlags("-W -Wall -I#include -I#boost -frounding-math "
                   "-DHAVE_CGAL -DUSE_CGAL_ON_INEXACT -lCGAL -lCGAL_Core"))

# Build flags.
if configuration == 'release':
    print "Using Release configuration."
    env.MergeFlags(env.ParseFlags("-O3 -g"))
elif configuration == 'valgrind':
    print "Using Valgrind configuration."
    env.MergeFlags(env.ParseFlags("-O -g -fno-inline"))
elif configuration == 'gprof':
    print "Using gprof configuration."
    env.MergeFlags(env.ParseFlags("-O2 -pg -lc"))
    env['LINKFLAGS'] += SCons.Util.CLVar('-pg')
else:
    # Debug configuration.
    print "Using Debug configuration."
    env.MergeFlags(env.ParseFlags("-O0"))

global_env.my_main_program = \
    env.Program(target="delaunay", source=['main.cpp'])

# vim: set filetype=python ts=4 sw=4 et:
