#  This file is part of Delaunay triangulation robust implementation.
#
#  Copyright (C) 2010, 2011  Vladimir Rutsky <altsysrq@gmail.com>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

import os.path
import itertools

import SCons.Util

Import('global_env')
env = global_env.Clone()

#env['Gch'] = env.Gch('precompiled.hpp')[0]

sources = ['main.cpp']

global_env.delaunay = \
    env.Program(target="delaunay", source=sources)

#env.MSVSProject(
#    target='delaunay' + env['MSVSPROJECTSUFFIX'],
#    srcs=sources,
#    #incs=barincs,
#    #localincs=barlocalincs,
#    #resources=barresources,
#    #misc=barmisc,
#    buildtarget=global_env.delaunay,
#    variant='Release')

# vim: set filetype=python ts=4 sw=4 et:
